import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';

interface ProphecyDisplayProps {
  prophecy: string;
  visible: boolean;
  onReset: () => void;
}

export const ProphecyDisplay: React.FC<ProphecyDisplayProps> = ({
  prophecy,
  visible,
  onReset
}) => {
  return (
    <AnimatePresence>
      {visible && (
        <motion.div
          className="absolute inset-0 flex items-center justify-center z-50 bg-black bg-opacity-80"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          exit={{ opacity: 0 }}
        >
          <motion.div
            className="relative max-w-md mx-4"
            initial={{ scale: 0, rotate: -10 }}
            animate={{ scale: 1, rotate: 0 }}
            exit={{ scale: 0, rotate: 10 }}
            transition={{ type: "spring", damping: 15 }}
          >
            {/* Toilet Paper Roll */}
            <div className="relative bg-white rounded-lg p-6 border-4 border-gray-300 shadow-2xl">
              {/* Perforated Edge */}
              <div className="absolute top-0 left-0 right-0 h-2 bg-gray-200 border-b-2 border-dashed border-gray-400"></div>
              
              {/* Prophecy Text */}
              <motion.div
                className="text-center py-4"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                transition={{ delay: 0.5 }}
              >
                <h3 className="text-lg font-bold text-purple-800 mb-4">
                  🔮 ORACLE'S PROPHECY 🔮
                </h3>
                <motion.p
                  className="text-gray-800 text-sm leading-relaxed mb-6"
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: 1 }}
                >
                  "{prophecy}"
                </motion.p>
                
                {/* Toilet Paper Branding */}
                <div className="text-xs text-gray-500 mb-4 border-t border-gray-300 pt-2">
                  Prophecy™ Brand Toilet Paper
                  <br />
                  "Wiping Away Uncertainty Since 2025"
                </div>
              </motion.div>

              {/* Action Buttons */}
              <motion.div
                className="flex gap-3 justify-center"
                initial={{ opacity: 0, y: 20 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: 1.5 }}
              >
                <button
                  onClick={onReset}
                  className="px-4 py-2 bg-purple-600 text-white rounded border-2 border-purple-800 hover:bg-purple-700 transition-colors text-xs font-bold"
                >
                  🔄 REVERSE FLUSH
                </button>
                <button
                  onClick={() => {
                    const text = `Oracle's Prophecy: "${prophecy}" - Generated by Eye Rub Oracle`;
                    navigator.clipboard.writeText(text);
                  }}
                  className="px-4 py-2 bg-green-600 text-white rounded border-2 border-green-800 hover:bg-green-700 transition-colors text-xs font-bold"
                >
                  📋 COPY PROPHECY
                </button>
              </motion.div>
            </div>

            {/* Toilet Paper Roll Effect */}
            <motion.div
              className="absolute -top-4 left-1/2 transform -translate-x-1/2 w-8 h-8 bg-white rounded-full border-2 border-gray-300"
              animate={{ rotate: 360 }}
              transition={{ repeat: Infinity, duration: 4, ease: "linear" }}
            >
              <div className="absolute inset-1 bg-gray-100 rounded-full"></div>
            </motion.div>
          </motion.div>
        </motion.div>
      )}
    </AnimatePresence>
  );
};